### ISSUE TITLE
I lost my all test database when I ran 'py.test [some options] tests/unit '. 

### ISSUE THREAD

**Issue by Youngsoo77** [kkamkou/gitmostwanted.com#174]
I am watching your amazing project well. I was able to run the program with your help.
Thank you very much.

So. I was running some test...

However my test environment database was all dropped all.
Although It was a test environment, but I thought it was odd that the database was all gone.

So. I set up the test database in gitmostwanted.config.py

The test proceeded in the order of the code below and deleted the existing database.
gitmostwanted.app.py
```python
app.config.from_object('gitmostwanted.config.Config' + env)
app.config.from_envvar('GMW_APP_SETTINGS', silent=True)
```

I think the order of the above code has changed. This is because the global configuration section overrides the environment settings.

Is there a problem with the order?
Is there a reason to drop the entire database when testing?
I think that It does not make sense to let the database disappear in the test environment.

I always thank you very deeply for your kind answers.
I hope you have a good day.

Youngsoo

**Comment by kkamkou** [comment]
Check out these lines:
- `tests/unit/test_web.py:17`
- `tests/unit/test_web.py:21`

By default, flask uses `sqlite` to emulate the database. I assume you put the real database data to the Testing section, or executed it without `GMW_APP_ENV` env. variable (which is a bug in the documentation and [I've updated it](https://github.com/kkamkou/gitmostwanted.com/commit/d42a4324abe324e329fdf5d621051d37cf01eaa9), thank you).

The order is correct. First, we're loading the `common` (default) preset, then we read data from a file overwriting any existing param. `from_envvar` is sugar for `from_pyfile`.

**Comment by Youngsoo77** [comment]
Oh Thank you for your reply.


I understood what was the problem.

have a nice day.

- youngsoo


2016-12-03 12:41 GMT+09:00 Kanstantsin Kamkou <notifications@github.com>:
