### ISSUE TITLE
Duplicate filter in the query

### ISSUE THREAD

**Issue by Youngsoo77** [kkamkou/gitmostwanted.com#175]
- gitmostwanted/tasks/repo_status.py:11

```python
def status_detect(num_days, num_segments):
    repos = Repo.query.filter().filter(Repo.status == 'unknown')
```

I think that 'filter()' seems to have duplicated.
If I'm wrong, plz tell me why.

**Comment by kkamkou** [comment]
Yes, it is typo. * nice catch.
