### ISSUE TITLE
why you stopped update news

### ISSUE THREAD

**Issue by mrtylerzhou** [kkamkou/gitmostwanted.com#214]

**Comment by kkamkou** [comment]
I'm using shared hosting and the load for some jobs are overwhelming. See more here: http://2ka.by/coffee?project=gitmostwanted.com. Hence the system crashed and can't recover. I'll try to reduce the amount of entries to process to fit the hosting.

**Comment by kkamkou** [comment]
Should work now. Thank you for the ticket.
