### ISSUE TITLE
[Trending] aplus-framework stuck in the trending page

### ISSUE THREAD

**Issue by daiyam** [kkamkou/gitmostwanted.com#246]
Hello,

A bunch of libraries from aplus-framework are stuck on the Trending page. It's been a few weeks like that. Not sure why.

**Comment by kkamkou** [comment]
Thank you for the issue. Will check it.

**Comment by daiyam** [comment]
Sorry but the issue is back.

**Comment by kkamkou** [comment]
This repository is spammed via bots right now, it looks like trying to represent in trends:
![image](https://user-images.githubusercontent.com/305739/193559506-6c69033e-b3fc-40aa-a5bb-3b940d2ae9d5.png)

This project is created to filter out such "individuals" in a long run, for now we can do nothing with it.
